// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: errors.proto

package example2

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Top-level error enum
type ErrorReason int32

const (
	// Unknown error
	ErrorReason_UNKNOWN ErrorReason = 0
	// Service unavailable
	ErrorReason_SERVICE_UNAVAILABLE ErrorReason = 1
	// Request timeout
	ErrorReason_REQUEST_TIMEOUT ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVICE_UNAVAILABLE",
		2: "REQUEST_TIMEOUT",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":             0,
		"SERVICE_UNAVAILABLE": 1,
		"REQUEST_TIMEOUT":     2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

// Nested error enum
type GetInfoResp_ErrorReason int32

const (
	// Unknown error
	GetInfoResp_UNKNOWN GetInfoResp_ErrorReason = 0
	// User not found
	GetInfoResp_USER_NOT_FOUND GetInfoResp_ErrorReason = 1
	// User already exists
	GetInfoResp_USER_ALREADY_EXISTS GetInfoResp_ErrorReason = 2
	// Invalid user data
	GetInfoResp_INVALID_USER_DATA GetInfoResp_ErrorReason = 3
)

// Enum value maps for GetInfoResp_ErrorReason.
var (
	GetInfoResp_ErrorReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER_NOT_FOUND",
		2: "USER_ALREADY_EXISTS",
		3: "INVALID_USER_DATA",
	}
	GetInfoResp_ErrorReason_value = map[string]int32{
		"UNKNOWN":             0,
		"USER_NOT_FOUND":      1,
		"USER_ALREADY_EXISTS": 2,
		"INVALID_USER_DATA":   3,
	}
)

func (x GetInfoResp_ErrorReason) Enum() *GetInfoResp_ErrorReason {
	p := new(GetInfoResp_ErrorReason)
	*p = x
	return p
}

func (x GetInfoResp_ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetInfoResp_ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[1].Descriptor()
}

func (GetInfoResp_ErrorReason) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[1]
}

func (x GetInfoResp_ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetInfoResp_ErrorReason.Descriptor instead.
func (GetInfoResp_ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0, 0}
}

// User info response
type GetInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResp) Reset() {
	*x = GetInfoResp{}
	mi := &file_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResp) ProtoMessage() {}

func (x *GetInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResp.ProtoReflect.Descriptor instead.
func (*GetInfoResp) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetInfoResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\aexample\x1a\x13errors/errors.proto\"\xc3\x01\n" +
	"\vGetInfoResp\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"|\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x1d\n" +
	"\x13USER_ALREADY_EXISTS\x10\x02\x1a\x04\xa8E\x99\x03\x12\x1b\n" +
	"\x11INVALID_USER_DATA\x10\x03\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03*`\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x1d\n" +
	"\x13SERVICE_UNAVAILABLE\x10\x01\x1a\x04\xa8E\xf7\x03\x12\x19\n" +
	"\x0fREQUEST_TIMEOUT\x10\x02\x1a\x04\xa8E\x98\x03\x1a\x04\xa0E\xf4\x03BGZEgithub.com/orzkratos/errgenkratos/internal/examples/example2;example2b\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errors_proto_goTypes = []any{
	(ErrorReason)(0),             // 0: example.ErrorReason
	(GetInfoResp_ErrorReason)(0), // 1: example.GetInfoResp.ErrorReason
	(*GetInfoResp)(nil),          // 2: example.GetInfoResp
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
		MessageInfos:      file_errors_proto_msgTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
