// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: errors.proto

package example3

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Global error codes for common issues
// 全局错误码，用于通用问题
type ErrorReason int32

const (
	// Unknown error
	ErrorReason_UNKNOWN ErrorReason = 0
	// Internal server error
	ErrorReason_INTERNAL_ERROR ErrorReason = 1
	// Service unavailable
	ErrorReason_SERVICE_UNAVAILABLE ErrorReason = 2
	// Request timeout
	ErrorReason_REQUEST_TIMEOUT ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "INTERNAL_ERROR",
		2: "SERVICE_UNAVAILABLE",
		3: "REQUEST_TIMEOUT",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":             0,
		"INTERNAL_ERROR":      1,
		"SERVICE_UNAVAILABLE": 2,
		"REQUEST_TIMEOUT":     3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\bexample3\x1a\x13errors/errors.proto*z\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x18\n" +
	"\x0eINTERNAL_ERROR\x10\x01\x1a\x04\xa8E\xf4\x03\x12\x1d\n" +
	"\x13SERVICE_UNAVAILABLE\x10\x02\x1a\x04\xa8E\xf7\x03\x12\x19\n" +
	"\x0fREQUEST_TIMEOUT\x10\x03\x1a\x04\xa8E\x98\x03\x1a\x04\xa0E\xf4\x03BGZEgithub.com/orzkratos/errgenkratos/internal/examples/example3;example3b\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: example3.ErrorReason
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
