// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: user_service.proto

package example3

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User status enum
// 用户状态枚举
type GetUserResponse_UserStatus int32

const (
	// Unknown status
	GetUserResponse_STATUS_UNKNOWN GetUserResponse_UserStatus = 0
	// Active user
	GetUserResponse_ACTIVE GetUserResponse_UserStatus = 1
	// Inactive user
	GetUserResponse_INACTIVE GetUserResponse_UserStatus = 2
	// Suspended user
	GetUserResponse_SUSPENDED GetUserResponse_UserStatus = 3
)

// Enum value maps for GetUserResponse_UserStatus.
var (
	GetUserResponse_UserStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "SUSPENDED",
	}
	GetUserResponse_UserStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"ACTIVE":         1,
		"INACTIVE":       2,
		"SUSPENDED":      3,
	}
)

func (x GetUserResponse_UserStatus) Enum() *GetUserResponse_UserStatus {
	p := new(GetUserResponse_UserStatus)
	*p = x
	return p
}

func (x GetUserResponse_UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserResponse_UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_service_proto_enumTypes[0].Descriptor()
}

func (GetUserResponse_UserStatus) Type() protoreflect.EnumType {
	return &file_user_service_proto_enumTypes[0]
}

func (x GetUserResponse_UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserResponse_UserStatus.Descriptor instead.
func (GetUserResponse_UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1, 0}
}

// GetUser-specific error codes
// GetUser特定错误码
type GetUserResponse_ErrorReason int32

const (
	// Unknown error
	GetUserResponse_UNKNOWN GetUserResponse_ErrorReason = 0
	// User not found
	GetUserResponse_USER_NOT_FOUND GetUserResponse_ErrorReason = 1
	// Access denied
	GetUserResponse_ACCESS_DENIED GetUserResponse_ErrorReason = 2
	// Invalid username
	GetUserResponse_INVALID_USER_ID GetUserResponse_ErrorReason = 3
)

// Enum value maps for GetUserResponse_ErrorReason.
var (
	GetUserResponse_ErrorReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER_NOT_FOUND",
		2: "ACCESS_DENIED",
		3: "INVALID_USER_ID",
	}
	GetUserResponse_ErrorReason_value = map[string]int32{
		"UNKNOWN":         0,
		"USER_NOT_FOUND":  1,
		"ACCESS_DENIED":   2,
		"INVALID_USER_ID": 3,
	}
)

func (x GetUserResponse_ErrorReason) Enum() *GetUserResponse_ErrorReason {
	p := new(GetUserResponse_ErrorReason)
	*p = x
	return p
}

func (x GetUserResponse_ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserResponse_ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_user_service_proto_enumTypes[1].Descriptor()
}

func (GetUserResponse_ErrorReason) Type() protoreflect.EnumType {
	return &file_user_service_proto_enumTypes[1]
}

func (x GetUserResponse_ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserResponse_ErrorReason.Descriptor instead.
func (GetUserResponse_ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1, 1}
}

// Get user request
// 获取用户信息请求
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username to query
	Username      int64 `protobuf:"varint,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUsername() int64 {
	if x != nil {
		return x.Username
	}
	return 0
}

// Get user response
// 获取用户信息响应
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Display name
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Current user status
	Status        GetUserResponse_UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=example3.GetUserResponse_UserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserResponse) GetStatus() GetUserResponse_UserStatus {
	if x != nil {
		return x.Status
	}
	return GetUserResponse_STATUS_UNKNOWN
}

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\bexample3\x1a\x13errors/errors.proto\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\x03R\busername\"\xc2\x02\n" +
	"\x0fGetUserResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12<\n" +
	"\x06status\x18\x03 \x01(\x0e2$.example3.GetUserResponse.UserStatusR\x06status\"I\n" +
	"\n" +
	"UserStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x03\"n\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x17\n" +
	"\rACCESS_DENIED\x10\x02\x1a\x04\xa8E\x93\x03\x12\x19\n" +
	"\x0fINVALID_USER_ID\x10\x03\x1a\x04\xa8E\x90\x032M\n" +
	"\vUserService\x12>\n" +
	"\aGetUser\x12\x18.example3.GetUserRequest\x1a\x19.example3.GetUserResponseBGZEgithub.com/orzkratos/errgenkratos/internal/examples/example3;example3b\x06proto3"

var (
	file_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_rawDescData []byte
)

func file_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_rawDescData
}

var file_user_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_service_proto_goTypes = []any{
	(GetUserResponse_UserStatus)(0),  // 0: example3.GetUserResponse.UserStatus
	(GetUserResponse_ErrorReason)(0), // 1: example3.GetUserResponse.ErrorReason
	(*GetUserRequest)(nil),           // 2: example3.GetUserRequest
	(*GetUserResponse)(nil),          // 3: example3.GetUserResponse
}
var file_user_service_proto_depIdxs = []int32{
	0, // 0: example3.GetUserResponse.status:type_name -> example3.GetUserResponse.UserStatus
	2, // 1: example3.UserService.GetUser:input_type -> example3.GetUserRequest
	3, // 2: example3.UserService.GetUser:output_type -> example3.GetUserResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
		EnumInfos:         file_user_service_proto_enumTypes,
		MessageInfos:      file_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
