// Code generated by protoc-gen-orzkratos-errors (errgenkratos). DO NOT EDIT.

package example1

import (
	errors "github.com/go-kratos/kratos/v2/errors"
	errgenkratos "github.com/orzkratos/errgenkratos"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// Unknown error
func IsUnknown(err error) bool {
	return errgenkratos.IsError(err, ErrorReason_UNKNOWN, 500)
}

// Unknown error
func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return errgenkratos.NewError(500, ErrorReason_UNKNOWN, format, args...)
}

// User not found
func IsUserNotFound(err error) bool {
	return errgenkratos.IsError(err, ErrorReason_USER_NOT_FOUND, 404)
}

// User not found
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errgenkratos.NewError(404, ErrorReason_USER_NOT_FOUND, format, args...)
}

// Invalid parameter
func IsInvalidParameter(err error) bool {
	return errgenkratos.IsError(err, ErrorReason_INVALID_PARAMETER, 400)
}

// Invalid parameter
func ErrorInvalidParameter(format string, args ...interface{}) *errors.Error {
	return errgenkratos.NewError(400, ErrorReason_INVALID_PARAMETER, format, args...)
}
