// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: errors.proto

package example4

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetOrder-specific error codes
// GetOrder特定错误码
type GetOrderResponse_ErrorCode int32

const (
	// Unknown error
	GetOrderResponse_UNKNOWN GetOrderResponse_ErrorCode = 0
	// Order not found
	GetOrderResponse_ORDER_NOT_FOUND GetOrderResponse_ErrorCode = 1
	// Order expired
	GetOrderResponse_ORDER_EXPIRED GetOrderResponse_ErrorCode = 2
	// Access denied
	GetOrderResponse_ACCESS_DENIED GetOrderResponse_ErrorCode = 3
)

// Enum value maps for GetOrderResponse_ErrorCode.
var (
	GetOrderResponse_ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "ORDER_NOT_FOUND",
		2: "ORDER_EXPIRED",
		3: "ACCESS_DENIED",
	}
	GetOrderResponse_ErrorCode_value = map[string]int32{
		"UNKNOWN":         0,
		"ORDER_NOT_FOUND": 1,
		"ORDER_EXPIRED":   2,
		"ACCESS_DENIED":   3,
	}
)

func (x GetOrderResponse_ErrorCode) Enum() *GetOrderResponse_ErrorCode {
	p := new(GetOrderResponse_ErrorCode)
	*p = x
	return p
}

func (x GetOrderResponse_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetOrderResponse_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (GetOrderResponse_ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x GetOrderResponse_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetOrderResponse_ErrorCode.Descriptor instead.
func (GetOrderResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{1, 0}
}

// Get order request
// 获取订单请求
type GetOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID to query
	OrderUuid     string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

// Get order response
// 获取订单响应
type GetOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderUuid string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// Product ID
	ProductUuid int64 `protobuf:"varint,2,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	// Order amount
	Amount        float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderResponse) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *GetOrderResponse) GetProductUuid() int64 {
	if x != nil {
		return x.ProductUuid
	}
	return 0
}

func (x *GetOrderResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\bexample4\x1a\x13errors/errors.proto\"0\n" +
	"\x0fGetOrderRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\"\xd9\x01\n" +
	"\x10GetOrderResponse\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12!\n" +
	"\fproduct_uuid\x18\x02 \x01(\x03R\vproductUuid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"k\n" +
	"\tErrorCode\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x19\n" +
	"\x0fORDER_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x17\n" +
	"\rORDER_EXPIRED\x10\x02\x1a\x04\xa8E\x9a\x03\x12\x17\n" +
	"\rACCESS_DENIED\x10\x03\x1a\x04\xa8E\x93\x032Q\n" +
	"\fOrderService\x12A\n" +
	"\bGetOrder\x12\x19.example4.GetOrderRequest\x1a\x1a.example4.GetOrderResponseBGZEgithub.com/orzkratos/errgenkratos/internal/examples/example4;example4b\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_errors_proto_goTypes = []any{
	(GetOrderResponse_ErrorCode)(0), // 0: example4.GetOrderResponse.ErrorCode
	(*GetOrderRequest)(nil),         // 1: example4.GetOrderRequest
	(*GetOrderResponse)(nil),        // 2: example4.GetOrderResponse
}
var file_errors_proto_depIdxs = []int32{
	1, // 0: example4.OrderService.GetOrder:input_type -> example4.GetOrderRequest
	2, // 1: example4.OrderService.GetOrder:output_type -> example4.GetOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
		MessageInfos:      file_errors_proto_msgTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
